[versions]
agp = "8.13.0"
kotlin = "2.2.20"
appcompat = "1.7.1"
material = "1.13.0"
coreKtx = "1.17.0"
fastkv = "3.0.1"
fastjson2 = "2.0.59"

[libraries]
appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }

#xposed api
xposed-api = { module = "de.robv.android.xposed:api", version = "82" }
dexkit = { module = "org.luckypray:dexkit", version = "2.0.7" }

fastkv = { group = 'io.github.billywei01', name = 'fastkv', version.ref = "fastkv" }
fastjson2 = { module = "com.alibaba.fastjson2:fastjson2", version.ref = "fastjson2" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
android-library = { id = "com.android.library", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
